### ISSUE TITLE
Take the name of the player as input and store the score of the person.

### ISSUE THREAD

**Issue by prithaupadhyay** [prithaupadhyay/Memory-Game#6]

**Comment by Vishal1541** [comment]
I want to work on this issue :smiley:

**Comment by Vishal1541** [comment]
@prithaupadhyay Please refer to the PR #33 
![name_input](https://user-images.githubusercontent.com/20883811/46622003-b8993e00-cb46-11e8-9aee-4fc78b266bf6.png)
![name_input2](https://user-images.githubusercontent.com/20883811/46622006-ba630180-cb46-11e8-8081-9ea71a438012.png)
